---
title: "Introduction to vdjmisc"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{introduction}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  fig.width = 7,
  fig.height = 4,
  comment = "#>"
)
```

```{r setup}
library(dplyr)
library(ggplot2)
library(vdjmisc)
library(patchwork)
theme_set(theme_minimal())
```

# Plot 10x data

```{r}
f <- list.files(file.path(system.file(package = "vdjmisc"), "extdata/10x"), full.names = TRUE)
f
```

## Reading one file

```{r warning=FALSE}
vdj <- read_vdj_10x(f[1])
vdj <- vdj %>% mutate(cell_index = barcode)
vdj
```


```{r}
vdj_tidy <- tidy_vdj_10x(vdj)
vdj_tidy
```


```{r}
plot_vdj_usage(vdj_tidy)
```

## Reading a batch of files

```{r}
path <- file.path(system.file(package = "vdjmisc"), "extdata/10x")
path
```


```{r warning=FALSE}
vdj <- read_vdj_10x_batch(path, extension = "csv.gz")
head(vdj)
```


```{r}
vdj <- vdj %>% mutate(samplename = sub(".csv.gz", "", basename(filename)))
head(vdj)
```


```{r}
vdj <- vdj %>% mutate(barcode = paste(samplename, barcode, sep = ":"))
head(vdj)
```


```{r}
vdj_tidy <- tidy_vdj_10x(vdj)
head(vdj_tidy)
```


```{r}
plot_vdj_usage(vdj_tidy)
```


```{r fig.height=8}
plot_vdj_usage(vdj_tidy, split.by = "samplename.a")
```

# Plot VDJdb data

## Reading the full file

```{r}
f <- list.files(file.path(system.file(package = "vdjmisc"), "extdata/vdjdb"), full.names = TRUE)
f
```


```{r}
vdjdb <- read_vdjdb_full(f, paired = TRUE)
vdjdb
```


```{r}
plot_vdj_usage(vdjdb)
```


```{r fig.height=8}
plot_vdj_usage(vdjdb, split.by = "antigen.species", order = TRUE) + plot_layout(ncol = 2)
```

